### PR TITLE
Demonstrate the `==` operator in README.md

### LINKED ISSUE #6: [FEATURE] Show `==` being used in the README examples
In the list of examples in the README, I wonder if it might be worth demonstrating something like:
```python3
fd4 = frozendict({"Sulla": "Marco", "Hicks": "Bill"})
fd4 is fd
# False

fd4 == fd
# True

fd5 = frozendict({"Hicks": "Bill", "Sulla": "Marco"})
fd5 == fd4
# True
```

Or maybe that's too trivial to be worth demonstrating? :man_shrugging:

### PR DESCRIPTION
**Pull request by lurch**
Fixes #6

### CODE REVIEW

**Comment by Marco-Sulla** [comment]
The `print` and the `hash` seems to me a bit too much :)

**Comment by lurch** [comment]
I added the `print` to show that `frozendict` also remembers the order of it's keys (just like a regular `dict` in Python3), and I added the `hash` to show that they hash to the same value even though the `repr` is different.
But happy to remove them again if you think they're superfluous.

**Comment by Marco-Sulla** [comment]
Ok for `print`, you convinced me. 
For hash, if they are equal and hashable, they _must_ have the same hash, or it's a bug :)

**Comment by lurch** [comment]
Removed `hash` example, as requested :)

**Pull request merged**
