### PR TITLE
updated some random code to replace my missing pull request

### PR DESCRIPTION
**Pull request by bessan75**

### CODE REVIEW

**Comment by lurch** [comment]
Huh?

**Comment by bessan75** [comment]
sorry, I just used it as an example of a pull request for my class.
Thanks

**Comment by lurch** [comment]
It's probably much better to create a pull request in e.g. https://github.com/bessan75/myrepo3 rather than polluting "real" GitHub repos with nonsense examples.

**Comment by Marco-Sulla** [comment]
Oh my god... X-D is there a way to block this guy?

**Comment by Marco-Sulla** [comment]
Done. He should be proud, (s)he had now something in common with Tim Peters X-D

**Pull request closed without merging**
